### ISSUE TITLE
Reroll of initiative in battle

### ISSUE THREAD

**Issue by Dan-True** [GrognardsFromHell/TemplePlus#312] opened 2018-10-21 13:12 UTC
When someone dies (or goes down?) there's often a reroll of inititive, which is causing some problems:

- It leaves everyone flatfooted in the middle of battle. This seems to be a bit too rogue-friendly.
- I've seen a web spell that had just been cast, expire the turn after because of this reroll.
- People sometime teleport slightly about to new positions. Once this left my carefully-placed-in-a-narrow-spot party fairly messed up. My cleric ended up on the other side of the corner and in the middle of a lot of enemies.

Has anyone else observed this behaviour?

- Dan

**Comment by DudeMcDude** [comment] 2018-10-21 13:42
Hmm, i did revamp the end-of-combat code a while ago, this may be a side effect.
It'd be best if you could produce a savegame that reliably demonstrates this.

**Comment by Dan-True** [comment] 2018-10-21 14:46
Hm... I can try.

**Comment by Dan-True** [comment] 2018-10-22 07:41
This is the fastest I could do. I can try to make something more specific when I have time, but it may be a few days.

[ToEE Save.zip](https://github.com/GrognardsFromHell/TemplePlus/files/2500490/ToEE.Save.zip)

This save is in the middle of combat, right after Lareth has died in the moathouse. The rest of the combat is just cleanup. After that, exit the mouthouse and you will be sprung by a large group of enemies. Cast Web on them, it should be prepared.

During the combat someone will go down and the web spell will end. I think it's only when someone dies, not just becomes unconscious. It also seems to be only named characters (PCs or named NPCs), not Gnolls or bandits etc.

As said, the above save requires a bit work before problem arises. But I will get it in a better state in a few days if needed.

**Comment by Dan-True** [comment] 2018-10-22 07:43
Regarding the teleportation, I find that it's not only at end-of-combat. It only happens when a character ends up standing on top of an unconscious/dead character. Then some events (like end of combat or targetting them with a spell) forces a replacement of them. I think I've only observed it for PCs.

- Dan

**Comment by Felipefpl** [comment] 2018-12-30 12:09
Sorry for the off-topic Dan-True and McDude but i didnt wanna start a new thread just for this:

Is there any list showing how many of the more than 500 vanilla bugs of TOEE were fixed by Temple Plus? I didnt see any list around showing this.

**Comment by DoctorBak** [comment] 2019-01-22 07:30
> Is there any list showing how many of the more than 500 vanilla bugs of TOEE were fixed by Temple Plus? I didnt see any list around showing this.

Search for the Atari Buglist on this [thread](https://rpgcodex.net/forums/index.php?threads/temple-changelog.99319/).

**Comment by DoctorBak** [comment] 2019-01-22 07:32
> Is there any list showing how many of the more than 500 vanilla bugs of TOEE were fixed by Temple Plus? I didnt see any list around showing this.

Search for the Atari Buglist in this [thread](https://rpgcodex.net/forums/index.php?threads/temple-changelog.99319/).

**Comment by DudeMcDude** [comment] 2019-01-22 15:40
Regarding the original issue, I could not reproduce it. Not saying it doesn't happen, but I can't do anything about it without reliable reproduction steps.

**Closed by DudeMcDude** 2019-01-22 15:40 UTC

**Comment by Felipefpl** [comment] 2019-01-27 12:59
DoctorBak - thank you for the link, didnt know that codex had a page for this, only for the full list of vanilla bugs.

**Comment by DudeMcDude** [comment] 2019-01-29 17:43
Ok, I finally managed to reproduce this issue. It happens when one of your characters die during an AoO. I guess I'm usually careful about taking AoO's so I didn't notice ;)
Fixed for next version, thanks for reporting!

**Comment by Dan-True** [comment] 2019-03-04 08:41
Thanks. Although I also experienced it when enemy combatants died in an AoE :)

**Comment by DudeMcDude** [comment] 2019-03-04 16:35
Have you experienced it in the latest release?
