### ISSUE TITLE
[BUG] Manyshot feat is not working

### ISSUE THREAD

**Issue by Erhog** [GrognardsFromHell/TemplePlus#374] opened 2020-01-16 15:25 UTC
Hi,
Manyshot feat isn't working at all - you could choose this feat and activate it, but penalty isn't applied and no bonus damage from additional arrows.

Feat explained:

Manyshot

You can fire multiple arrows simultaneously against a nearby target.

Prerequisite: Point Blank Shot (PH) , Rapid Shot (PH) , DEX 17, base attack bonus +6,

Benefit:
As a standard action, you may fire two arrows at a single opponent within 30 feet. Both arrows use the same attack roll (with a -4 penalty) to determine success and deal damage normally (but see Special). For every five points of base attack bonus you have above +6, you may add one additional arrow to this attack, to a maximum of four arrows at a base attack bonus of +16. However, each arrow after the second adds a cumulative -2 penalty on the attack roll (for a total penalty of -6 for three arrows and -8 for four). Damage reduction and other resistances apply separately against each arrow fired.
Special

Regardless of the number of arrows you fire, you apply precision-based damage (such as sneak attack damage) only once. If you score a critical hit, only the first arrow fired deals critical damage; all others deal regular damage. A fighter may select Manyshot as one of his fighter bonus feats (see page 38). A 6th-level ranger who has chosen the archery combat style is treated as having Manyshot even if he does not have the prerequisites for it, but only when he is wearing light or no armor (see page 48).

http://dnd.arkalseif.info/feats/epic-level-handbook--41/manyshot--1845/index.html

**Comment by doug1234** [comment] 2020-01-17 02:05
I should have time tomorrow to try to reproduce this issue.

**Comment by DudeMcDude** [comment] 2020-01-17 15:10
Are you using single attack?
IIRC it only works that way, and not when it's part of a full attack.

**Comment by valepu** [comment] 2020-01-17 15:15
Can confirm Multishot can be used only as a single attack (or better it requires a standard action, you can't even use it with Shot On The Run feat since that feat lets you do only an "attack action")

**Comment by Erhog** [comment] 2020-01-17 17:19
Full attack, single attack - not working in any case in game.

Manyshot is standard action which means you could move before or after as usual standard action - this is the point of ability.

**Comment by doug1234** [comment] 2020-01-18 01:47
It does indeed seem to be broken in temple+.

**Comment by doug1234** [comment] 2020-01-18 04:39
Looks like attackPacket.dispKey is getting set to zero which causes the function at 100FCF50 not to set the flag D20CAF_MANYSHOT for the attack packet.  Not sure why it is getting set to zero yet.  I am going to look into it a bit more when I have time.

**Comment by doug1234** [comment] 2020-01-18 14:04
I think I will rewrite the function at 100FCF50.  I don't see any reason it needs to check that key.  I may also fix the attack bonus in the other function which is wrong.

**Comment by DudeMcDude** [comment] 2020-01-18 14:37
I'd much rather look into the root cause of this than issue an ad hoc fix for manyshot.

**Comment by doug1234** [comment] 2020-01-18 21:18
There could be a fundamental issue that needs to be fixed but I don't see why the function is checking attackPacket.dispKey at all.  The bonus in that function is actually incorrect anyway so it should be replaced.  I also don't think the function works correctly for characters with 3 or more attacks.

**Comment by doug1234** [comment] 2020-01-22 04:25
Added my change to my current pull request.

**Comment by doug1234** [comment] 2020-03-26 02:23
This has been fixed for a while.  I am going to go ahead and close it out.

**Closed by doug1234** 2020-03-26 02:23 UTC
