### ISSUE TITLE
Error loading saved games

### ISSUE THREAD

**Issue by pelador** [GrognardsFromHell/TemplePlus#122] opened 2016-01-22 17:31 UTC
I attempt to load a saved game and then I get an error and a crash to desktop. I can load saved files when I exit to the main menu screen but if I close the app and restart then it crashes when I try to load my saves. 

Dump Summary
------------
Dump File:	44fd9219-eabc-4b43-a6b8-249ed4780760.dmp : C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\44fd9219-eabc-4b43-a6b8-249ed4780760.dmp
Last Write Time:	22-Jan-16 5:13:01 PM
Process Name:	TemplePlus.exe : C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\TemplePlus.exe
Process Architecture:	x86
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Not Present

System Information
------------------
OS Version:	6.2.9200
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
TemplePlus.exe	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\TemplePlus.exe	0.0.0.0
ntdll.dll	C:\Windows\System32\ntdll.dll	6.2.10240.16603
kernel32.dll	C:\Windows\System32\kernel32.dll	6.2.10240.16384
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	6.2.10240.16384
apphelp.dll	C:\Windows\System32\apphelp.dll	6.2.10240.16384
user32.dll	C:\Windows\System32\user32.dll	6.2.10240.16603
gdi32.dll	C:\Windows\System32\gdi32.dll	6.2.10240.16644
advapi32.dll	C:\Windows\System32\advapi32.dll	6.2.10240.16644
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.10240.16384
sechost.dll	C:\Windows\System32\sechost.dll	6.2.10240.16384
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	6.2.10240.16412
sspicli.dll	C:\Windows\System32\sspicli.dll	6.2.10240.16384
CRYPTBASE.dll	C:\Windows\System32\CRYPTBASE.dll	6.2.10240.16384
bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	6.2.10240.16384
shell32.dll	C:\Windows\System32\shell32.dll	6.2.10240.16542
windows.storage.dll	C:\Windows\System32\windows.storage.dll	6.2.10240.16515
combase.dll	C:\Windows\System32\combase.dll	6.2.10240.16384
shlwapi.dll	C:\Windows\System32\shlwapi.dll	6.2.10240.16384
kernel.appcore.dll	C:\Windows\System32\kernel.appcore.dll	6.2.10240.16384
SHCore.dll	C:\Windows\System32\SHCore.dll	6.2.10240.16384
powrprof.dll	C:\Windows\System32\powrprof.dll	6.2.10240.16384
profapi.dll	C:\Windows\System32\profapi.dll	6.2.10240.16384
oleaut32.dll	C:\Windows\System32\oleaut32.dll	6.2.10240.16384
ws2_32.dll	C:\Windows\System32\ws2_32.dll	6.2.10240.16384
nsi.dll	C:\Windows\System32\nsi.dll	6.2.10240.16384
bcrypt.dll	C:\Windows\System32\bcrypt.dll	6.2.10240.16384
imm32.dll	C:\Windows\System32\imm32.dll	6.2.10240.16384
msctf.dll	C:\Windows\System32\msctf.dll	6.2.10240.16384
dbghelp.dll	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\dbghelp.dll	6.3.17.0
temple.dll	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\temple.dll	0.0.0.0
ole32.dll	C:\Windows\System32\ole32.dll	6.2.10240.16384
pyToEE22.dll	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\pyToEE22.dll	2.2.15.1011
Mss32.dll	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\Mss32.dll	3.0.0.0
d3d8.dll	C:\Windows\System32\d3d8.dll	6.2.10240.16384
winmm.dll	C:\Windows\System32\winmm.dll	6.2.10240.16384
binkw32.dll	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\binkw32.dll	1.5.10.0
dinput8.dll	C:\Windows\System32\dinput8.dll	6.2.10240.16384
tio.dll	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\tio.dll	0.0.0.0
msvcr71.dll	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\msvcr71.dll	7.10.3052.4
d3d8thk.dll	C:\Windows\System32\d3d8thk.dll	6.2.10240.16384
dwmapi.dll	C:\Windows\System32\dwmapi.dll	6.2.10240.16392
WINMMBASE.dll	C:\Windows\System32\WINMMBASE.dll	6.2.10240.16384
cfgmgr32.dll	C:\Windows\System32\cfgmgr32.dll	6.2.10240.16384
zlib-1.2.1.dll	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\zlib-1.2.1.dll	1.2.1.0
devobj.dll	C:\Windows\System32\devobj.dll	6.2.10240.16384
uxtheme.dll	C:\Windows\System32\uxtheme.dll	6.2.10240.16397
d3d9.dll	C:\Windows\System32\d3d9.dll	6.2.10240.16412
aticfx32.dll	C:\Windows\System32\aticfx32.dll	8.17.10.1404
version.dll	C:\Windows\System32\version.dll	6.2.10240.16384
atiu9pag.dll	C:\Windows\System32\atiu9pag.dll	8.14.1.6463
atiumdag.dll	C:\Windows\System32\atiumdag.dll	9.14.10.1128
atiumdva.dll	C:\Windows\System32\atiumdva.dll	8.14.10.513
mssmp3.asi	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\miles\mssmp3.asi	0.0.0.0
mssvoice.asi	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\miles\mssvoice.asi	0.0.0.0
mssa3d.m3d	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\miles\mssa3d.m3d	0.0.0.0
mssds3d.m3d	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\miles\mssds3d.m3d	0.0.0.0
mssdx7.m3d	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\miles\mssdx7.m3d	0.0.0.0
msseax.m3d	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\miles\msseax.m3d	0.0.0.0
mssrsx.m3d	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\miles\mssrsx.m3d	0.0.0.0
msacm32.dll	C:\Windows\System32\msacm32.dll	6.2.10240.16384
msssoft.m3d	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\miles\msssoft.m3d	0.0.0.0
mssdsp.flt	C:\Program Files (x86)\GalaxyClient\Games\Temple of Elemental Evil\miles\mssdsp.flt	3.0.0.0
dsound.dll	C:\Windows\System32\dsound.dll	6.2.10240.16384
clbcatq.dll	C:\Windows\System32\clbcatq.dll	2001.12.10941.16384
MMDevAPI.dll	C:\Windows\System32\MMDevAPI.dll	6.2.10240.16384
propsys.dll	C:\Windows\System32\propsys.dll	7.0.10240.16384
AudioSes.dll	C:\Windows\System32\AudioSes.dll	6.2.10240.16515
WinTypes.dll	C:\Windows\System32\WinTypes.dll	6.2.10240.16384
avrt.dll	C:\Windows\System32\avrt.dll	6.2.10240.16384

**Comment by DudeMcDude** [comment] 2016-01-22 18:17
Hello pellador, 

can you upload the logfile (TemplePlus.log) and the crash dump file (the one that ends in .dmp )?

**Comment by pelador** [comment] 2016-01-22 18:41
Here are my latest dump and log files.

[e2953175-a126-42fb-ae81-9154312070a3.zip](https://github.com/GrognardsFromHell/TemplePlus/files/101251/e2953175-a126-42fb-ae81-9154312070a3.zip)


[TemplePlus.zip](https://github.com/GrognardsFromHell/TemplePlus/files/101250/TemplePlus.zip)

**Comment by DudeMcDude** [comment] 2016-01-22 23:06
A few more questions:
1. What ToEE version are you using? From the log file it looks like the GoG + Co8 modpack version.
2. When this crash happened, were you using build 412?
3. Does the savegame originate in a different version (e.g. from a game without TemplePlus)

**Comment by pelador** [comment] 2016-01-23 02:17
1. Yes Gog + Co8. 
2. 0.1.0-pre+412.
3. No it does not. I made the character in TemplePlus and played until I reached Homlett where I saved the game.

**Comment by DudeMcDude** [comment] 2016-01-23 09:33
Can't replicate the error here... I thought it had to do with installing the game in the program files folder, but that doesn't appear to cause any problems (for me at least).

Can you upload the savegame files?

**Comment by pelador** [comment] 2016-01-23 12:40
[Save.zip](https://github.com/GrognardsFromHell/TemplePlus/files/101854/Save.zip)

**Comment by DudeMcDude** [comment] 2016-01-23 13:39
Gotta say I'm stumped, because I can load these saves just fine... from the crash dump it looks like some sort of data corruption, but I can't trace the cause.

We're going to have a new public build in the next few weeks that has more detailed debug information, hopefully it will allow us to solve the problem.

**Comment by pelador** [comment] 2016-01-23 14:01
Ok thanks for your help. I'll try reinstalling everything and if that doesn't work then I'll just have to be patient.

**Comment by DudeMcDude** [comment] 2016-02-22 22:08
Hi Pelador, if you're still following:

The latest alpha builds should have more detailed feedback when / if something goes wrong. I'm closing the issue for now, if something else pops up let us know. Also the "unknown game version" issue has been fixed :)

**Closed by DudeMcDude** 2016-02-22 22:08 UTC
