### ISSUE TITLE
Render issue

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#88] opened 2015-07-04 06:27 UTC
http://i.imgur.com/n7ZYIg8.jpg

**Comment by DudeMcDude** [comment] 2015-09-17 09:02
Possibly related - trees in Hommlet not rendering right, and I think also not playing the swaying animations.
http://imgur.com/fGOZO8A

**Comment by shartte** [comment] 2015-09-24 23:17
Re: your initial bugreport: this bug is also present in vanilla (no co8) on windows 10.

**Comment by shartte** [comment] 2015-09-24 23:18
Also figured out what the issue is: Ferns require Alpha Testing to be enabled, but never actually set it to being required. (Actuall none of the Textured shaders do)

**Comment by shartte** [comment] 2015-09-24 23:29
Issue is fixed now. I added a hack to explicitly set the alpha testing to true for all "Textured" MDF files (most of them, including the fern).

This might actually have fixed your tree rendering issue, can you check?

**Closed** 2015-09-24 23:28 UTC
